# These are supported funding model platforms

github: CyberPunkMetalHead
Bitcoin: 1B4no1sJxCo44XFGoEoQQ4XfnWSrR6tCCU
Ethereum: 0x9875aC298d8DDF2faB196D81352268AFa0005d3d
Polkadot: 14YRqN43pY27Sw1mLMVKt6t3Fek139S12UMmPFdiZ1cRMLpE
Bitcoin Cash: qrumfx0vt4xxrwjxct0dzujwfggldvxs65hqppltxr
Monero: 8AhDdFtCZbXf6yuJ3novtk5w8MCpVMtjzKv6ZtrrubVJV5ijuK3EpfDALbcP3kYDZoJyN8jEXVShnNYLBrLib5poAL6qRGv
